verbs = {
    "suggest",
    "assist",
    "become",
    "feel",
    "expand",
    "form",
    "run",
    "use",
    "wait",
    "mention",
    "propose",
    "exclude",
    "hug",
    "dream",
    "start",
    "break",
    "critic",
    "advise",
    "argue",
    "need",
    "set",
    "engage",
    "listen",
    "throw",
    "control",
    "question",
    "drive",
    "collect",
    "act",
    "ask",
    "consume",
    "invite",
    "turn",
    "justify",
    "forgive",
    "discover",
    "compete",
    "recognize",
    "speak",
    "come",
    "prefer",
    "show",
    "update",
    "arrange",
    "meet",
    "improve",
    "contain",
    "continue",
    "add",
    "find",
    "clarify",
    "count",
    "guess",
    "check",
    "return",
    "cooperate",
    "decide",
    "criticize",
    "build",
    "succeed",
    "jump",
    "enable",
    "live",
    "believe",
    "educate",
    "warn",
    "open",
    "walk",
    "express",
    "carry",
    "go",
    "free",
    "visit",
    "quit",
    "think",
    "copy",
    "attend",
    "begin",
    "appeal",
    "learn",
    "laugh",
    "inform",
    "convince",
    "love",
    "motivate",
    "sing",
    "invent",
    "consider",
    "forget",
    "fix",
    "grow",
    "donate",
    "follow",
    "put",
    "avoid",
    "remember",
    "want",
    "understand",
    "celebrate",
    "teach",
    "deny",
    "repeat",
    "do",
    "know",
    "maintain",
    "obtain",
    "benefit",
    "experience",
    "observe",
    "answer",
    "attack",
    "demand",
    "call",
    "stand",
    "calculate",
    "explain",
    "study",
    "notice",
    "pass",
    "participate",
    "gather",
    "complete",
    "smell",
    "clean",
    "spend",
    "approach",
    "resolve",
    "offer",
    "sleep",
    "achieve",
    "tell",
    "prepare",
    "publish",
    "drop",
    "change",
    "combine",
    "inspire",
    "keep",
    "attempt",
    "introduce",
    "divide",
    "fight",
    "read",
    "require",
    "drink",
    "stop",
    "arrive",
    "write",
    "burn",
    "correct",
    "provide",
    "communicate",
    "prove",
    "design",
    "influence",
    "touch",
    "climb",
    "construct",
    "consult",
    "display",
    "behave",
    "dance",
    "support",
    "alter",
    "wonder",
    "compare",
    "move",
    "catch",
    "connect",
    "respond",
    "sign",
    "memorize",
    "fail",
    "include",
    "share",
    "look",
    "describe",
    "request",
    "admire",
    "identify",
    "develop",
    "challenge",
    "help",
    "give",
    "try",
    "eat",
    "borrow",
    "analyze",
    "organize",
    "protect",
    "appreciate",
    "ignore",
    "bring",
    "see",
    "get",
    "manage",
    "watch",
    "promise",
    "hang",
    "create",
    "measure",
    "enhance",
    "enjoy",
    "discuss",
    "save",
    "examine",
    "handle",
    "defend",
    "imagine",
    "destroy",
    "train",
    "bend",
    "choose",
    "jog",
    "hope",
    "charge",
    "worry",
    "take",
    "talk",
    "appear",
    "encourage",
    "contribute",
    "care",
    "play",
    "reduce",
    "relax",
    "thank",
    "shout",
    "leave",
    "allow",
    "accept",
    "adapt",
    "prevent",
    "insist",
    "work",
    "explore",
    "attract",
    "produce",
    "plan",
    "bounce",
    "deliver",
    "balance",
    "send",
}



nouns = {
    "ability", "accident", "account", "act", "action", "activity", "actor", "addition", "address", "advertisement",
    "advice", "affair", "age", "agency", "agreement", "air", "airport", "alarm", "ambition", "amount",
    "analysis", "anger", "animal", "answer", "anxiety", "apartment", "appeal", "apple", "application", "appointment",
    "area", "argument", "arm", "army", "arrival", "art", "article", "artist", "aspect", "assignment",
    "association", "assumption", "atmosphere", "attack", "attempt", "attention", "attitude", "audience", "author", "authority",
    "back", "background", "balance", "ball", "band", "bank", "bar", "base", "basis", "battle",
    "beach", "bear", "beauty", "bed", "beginning", "behavior", "belief", "bell", "benefit", "bird",
    "birth", "bit", "board", "boat", "body", "bone", "book", "border", "boss", "bottle",
    "bottom", "box", "boy", "brain", "branch", "bread", "break", "breakfast", "breath", "bridge",
    "brother", "budget", "building", "bus", "business", "button", "buyer", "cable", "cake", "camera",
    "campaign", "candidate", "capital", "car", "card", "care", "career", "carpet", "case", "cash",
    "cat", "category", "cause", "celebration", "cell", "center", "ceremony", "chain", "chair", "challenge",
    "chance", "change", "channel", "chapter", "character", "charge", "charity", "chart", "cheek", "chest",
    "chicken", "child", "choice", "church", "cigarette", "city", "claim", "class", "classroom", "climate",
    "clock", "clothes", "cloud", "club", "coach", "coal", "coast", "coat", "code", "coffee",
    "cold", "collar", "collection", "college", "combination", "comfort", "comment", "committee", "communication", "community",
    "company", "comparison", "competition", "complaint", "complex", "computer", "concept", "concern", "concert", "condition",
    "conference", "confidence", "connection", "consequence", "consideration", "construction", "contact", "content", "contest", "context",
    "contract", "control", "conversation", "conversion", "cook", "cookie", "copy", "corner", "cost", "count",
    "country", "county", "couple", "courage", "course", "court", "cousin", "cover", "cow", "crack",
    "craft", "crash", "cream", "creation", "crew", "criticism", "cross", "crowd", "crown", "culture",
    "cup", "currency", "customer", "cut", "cycle", "dad", "damage", "dance", "danger", "dark",
    "data", "date", "daughter", "day", "deal", "dealer", "death", "debate", "debt", "decision",
    "deed", "degree", "delay", "delivery", "demand", "department", "departure", "dependence", "depth", "description",
    "design", "desire", "desk", "detail", "development", "device", "devil", "diamond", "diet", "difference",
    "difficulty", "dinner", "direction", "director", "dirt", "disaster", "discipline", "discussion", "disease", "dish",
    "disk", "display", "distance", "distribution", "district", "doctor", "document", "dog", "door", "dot",
    "double", "doubt", "draft", "drama", "drawer", "dream", "dress", "drink", "drive", "driver",
    "drop", "drug", "drum", "duty", "ear", "earth", "ease", "east", "economics", "economy",
    "edge", "editor", "education", "effect", "effort", "egg", "election", "elevator", "emotion", "emphasis",
    "employer", "employment", "end", "energy", "engine", "engineer", "entertainment", "enthusiasm", "entrance", "entry",
    "environment", "episode", "equation", "equipment", "error", "escape", "essay", "estate", "estimate", "event",
    "exam", "examination", "example", "exchange", "excitement", "exercise", "existence", "expansion", "experience", "experiment",
    "expert", "explanation", "expression", "extension", "extent", "eye", "face", "fact", "factor", "fail",
    "failure", "fall", "family", "fan", "farm", "farmer", "fashion", "father", "fault", "fear",
    "feature", "fee", "feeling", "female", "field", "fight", "figure", "file", "film", "final",
    "finance", "finding", "finger", "finish", "fire", "fish", "fishing", "floor", "flower", "focus",
    "fold", "food", "foot", "football", "force", "forest", "form", "fortune", "foundation", "frame",
    "freedom", "friend", "friendship", "front", "fruit", "fuel", "fun", "function", "fund", "funeral",
    "future", "gain", "game", "gap", "garage", "garden", "gas", "gate", "gathering", "gear",
    "gene", "generation", "gift", "girl", "glass", "glove", "goal", "god", "gold", "golf",
    "good", "government", "grand", "grandfather", "grandmother", "grass", "greeting", "ground", "group", "growth",
    "guest", "guide", "guitar", "habit", "hair", "half", "hall", "hand", "handle", "happiness",
    "hat", "hate", "head", "health", "hearing", "heart", "heat", "height", "hell", "help",
    "hero", "hill", "history", "holiday", "home", "honey", "hook", "hope", "hospital", "host",
    "hotel", "hour", "house", "housing", "human", "hunger", "hunt", "hurry", "hurt", "husband",
    "idea", "ideal", "identity", "income", "independence", "indication", "industry", "inflation", "influence", "information",
    "injury", "insect", "inspection", "inspector", "instance", "instruction", "insurance", "intention", "interaction", "interest",
    "internet", "interview", "introduction", "investment", "invitation", "iron", "island", "issue", "item", "jacket",
    "job", "journey", "judge", "judgment", "juice", "jump", "junior", "jury", "keeper", "key",
    "kind", "king", "kitchen", "knee", "knife", "knowledge", "lab", "lack", "ladder", "lady",
    "lake", "land", "landscape", "language", "laugh", "law", "lawyer", "layer", "lead", "leader",
    "leadership", "league", "leather", "leave", "lecture", "length", "lesson", "letter", "level", "library",
    "life", "lift", "light", "limit", "line", "link", "lip", "list", "literature", "location",
    "lock", "log", "long", "look", "loss", "love", "luck", "lunch", "machine", "magazine",
    "mail", "main", "maintenance", "major", "make", "man", "management", "manager", "manner", "map",
    "mark", "market", "marketing", "marriage", "match", "material", "math", "matter", "meal", "meaning",
    "measurement", "meat", "media", "medicine", "medium", "meeting", "member", "membership", "memory", "mention",
    "menu", "mess", "message", "metal", "method", "middle", "might", "machine", "magazine", "magic", "maid", "mail", "mammal", "manager", "mansion", "market", "marriage",
    "mask", "match", "meal", "meaning", "measurement", "mechanism", "medicine", "meeting", "member", "memory",
    "message", "metal", "method", "midnight", "migration", "milestone", "military", "mill", "millionaire", "mind",
    "mine", "minister", "minute", "miracle", "mirror", "mission", "mixture", "mobile", "model", "moment",
    "monitor", "monkey", "monster", "month", "moon", "morning", "motion", "mountain", "mouse", "movement",
    "mystery", "myth", "nail", "name", "nation", "native", "nature", "navy", "necklace", "needle",
    "negotiation", "neighbor", "network", "newspaper", "night", "noise", "notebook", "notice", "novel", "number",
    "nutrition", "object", "obligation", "observation", "ocean", "offense", "officer", "operation", "opinion", "opportunity",
    "orange", "orbit", "order", "organization", "origin", "output", "oval", "owner", "oxygen", "package",
    "painting", "palace", "panel", "paper", "paragraph", "parent", "park", "partner", "party", "passenger",
    "passion", "passport", "pattern", "pause", "payment", "pearl", "pedal", "penalty", "pencil", "people",
    "percentage", "performance", "period", "permission", "person", "perspective", "pet", "philosophy", "photo", "phrase",
    "physics", "picture", "piece", "pilot", "pine", "planet", "plant", "platform", "player", "pleasure",
    "poem", "poet", "point", "poison", "policy", "pollution", "population", "position", "possibility", "postcard",
    "poster", "pot", "potential", "practice", "prayer", "prediction", "preference", "preparation", "presence", "pressure",
    "price", "priest", "prince", "principle", "prison", "prize", "problem", "process", "product", "profession",
    "profit", "program", "progress", "project", "promise", "promotion", "property", "proposal", "protection", "protest",
    "publication", "purpose", "puzzle", "quality", "quantity", "queen", "question", "quote", "rabbit", "radar",
    "radio", "railway", "rainbow", "range", "reaction", "reader", "reality", "reason", "recipe", "recognition",
    "record", "recovery", "refrigerator", "region", "relationship", "reliability", "relief", "remedy", "reminder", "report",
    "republic", "request", "research", "resolution", "resource", "respect", "responsibility", "restaurant", "result", "revolution",
    "reward", "rhythm", "riddle", "ring", "river", "road", "robot", "role", "room", "routine",
    "ruby", "rule", "rumor", "runner", "safety", "salary", "salt", "sample", "sand", "satellite", "sauce", "scale", "scene", "schedule",
    "school", "science", "sculpture", "season", "secret", "security", "seed", "selection", "sensation", "sentence",
    "sequence", "service", "shadow", "shelter", "shield", "shift", "ship", "shirt", "shock", "shopping",
    "shortage", "shoulder", "shower", "signal", "signature", "silence", "silver", "simplicity", "singer", "situation",
    "skill", "skin", "skull", "sky", "slave", "sleep", "slice", "slide", "smile", "smoke",
    "snake", "snow", "soap", "society", "software", "soil", "soldier", "solution", "song", "sort",
    "soul", "sound", "source", "space", "speaker", "specialist", "species", "speech", "speed", "spider",
    "spirit", "spoon", "sports", "spring", "square", "stability", "stage", "stair", "stamp", "standard",
    "star", "statement", "station", "statue", "status", "steak", "steam", "steel", "stem", "step",
    "stomach", "stone", "store", "storm", "story", "strategy", "stream", "street", "strength", "structure",
    "student", "studio", "study", "style", "substance", "success", "sugar", "suggestion", "suit", "summer",
    "sun", "supermarket", "support", "surface", "surprise", "survey", "survival", "swim", "symbol", "sympathy",
    "system", "table", "tablet", "talent", "target", "task", "taste", "tax", "teacher", "team",
    "technology", "temperature", "temple", "tendency", "tent", "term", "territory", "test", "theater", "theme",
    "theory", "therapist", "thing", "thought", "thread", "throat", "throne", "ticket", "tiger", "time",
    "title", "tone", "tool", "tooth", "topic", "tower", "trade", "tradition", "traffic", "training",
    "transaction", "transfer", "transition", "transport", "trap", "travel", "treasure", "tree", "trend", "trial",
    "triangle", "trick", "trip", "truck", "trust", "truth", "tunnel", "type", "umbrella", "union",
    "universe", "university", "user", "vacation", "valley", "value", "vampire", "variety", "vehicle", "venture",
    "version", "vessel", "village", "violin", "vision", "visitor", "voice", "volume", "volunteer", "voter",
    "vow", "voyage", "wall", "war", "warning", "warrior", "waste", "water", "wealth", "weapon",
    "weather", "wedding", "week", "weight", "welcome", "wheel", "whisper", "whistle", "width", "wind",
    "window", "wine", "winner", "winter", "wish", "witness", "wolf", "woman", "wonder", "wood",
    "wool", "word", "work", "worker", "world", "worm", "wound", "writer", "yard", "year",
    "yogurt", "youth", "zebra", "zero", "zone", "zoo"}




adjectives = {
    "beautiful", "angry", "brave", "calm", "cheerful", "brilliant", "bold", "careful", "careless", "confident",
    "delicate", "daring", "elegant", "energetic", "faithful", "friendly", "graceful", "happy", "harsh", "honest",
    "joyful", "kind", "lazy", "loyal", "lucky", "modest", "mysterious", "optimistic", "organized", "peaceful",
    "patient", "powerful", "proud", "quick", "quiet", "realistic", "reckless", "romantic", "shy", "smart",
    "strong", "silly", "timid", "trustworthy", "vivid", "vulnerable", "warm", "wise", "young", "adventurous",
    "affectionate", "ambitious", "arrogant", "attractive", "average", "beautiful", "benevolent", "bitter", "brilliant",
    "caring", "charming", "cheerful", "chilly", "compassionate", "composed", "conscientious", "considerate", "cordial",
    "courteous", "creative", "curious", "cynical", "dangerous", "decisive", "determined", "dynamic", "eager", "eager",
    "eerie", "emotional", "energetic", "enlightened", "envious", "expressive", "extroverted", "extraordinary", "fancy",
    "fierce", "fiery", "foolish", "frantic", "friendly", "funny", "generous", "gentle", "genuine", "gracious",
    "hardworking", "harmonious", "honorable", "humble", "imaginative", "incredible", "independent", "intelligent",
    "jovial", "joyful", "keen", "kind-hearted", "loyal", "magnetic", "mature", "mighty", "mysterious", "naive",
    "nervous", "optimistic", "outgoing", "patient", "peaceful", "persistent", "playful", "positive", "pragmatic",
    "reliable", "respectful", "righteous", "romantic", "shiny", "sincere", "sociable", "strong", "stubborn", "sweet",
    "talented", "tender", "thoughtful", "unpredictable", "understanding", "vibrant", "wise", "witty", "zealous",
    "adventurous", "affectionate", "aggressive", "alert", "amiable", "antagonistic", "apprehensive", "artificial",
    "attentive", "authoritative", "benevolent", "bitter", "boastful", "bored", "brash", "brave", "broad-minded",
    "busy", "cautious", "charming", "cheerful", "chilly", "clumsy", "compassionate", "confident", "cool-headed",
    "cowardly", "curious", "cynical", "dangerous", "decisive", "demanding", "detached", "diligent", "dynamic", "eager",
    "energetic", "extroverted", "famous", "fiery", "flamboyant", "friendly", "gentle", "genuine", "goofy", "grateful",
    "harsh", "honorable", "humorous", "imaginative", "impulsive", "intelligent", "irritable", "jovial", "joyful",
    "keen", "kind", "lazy", "loyal", "mature", "mean", "mischievous", "mysterious", "optimistic", "outgoing",
    "patient", "playful", "polite", "quick-witted", "reliable", "respectful", "romantic", "silly", "sincere", "stubborn",
    "strong-willed", "sweet", "talented", "trustworthy", "understanding", "vibrant", "wise", "zealous", "adventurous",
    "affectionate", "ambitious", "angry", "anxious", "apprehensive", "artistic", "athletic", "attentive", "benevolent",
    "bold", "bored", "careful", "charming", "cheerful", "compassionate", "confident", "curious", "determined", "dynamic",
    "empathetic", "energetic", "enthusiastic", "extroverted", "friendly", "gentle", "genuine", "graceful", "helpful",
    "honest", "hospitable", "imaginative", "intelligent", "irritated", "joyful", "keen", "kind", "loyal", "optimistic",
    "patient", "playful", "practical", "quick", "respectful", "romantic", "shy", "sincere", "strong", "thoughtful",
    "understanding", "vibrant", "wise", "zealous", "adventurous", "angry", "bitter", "brave", "careful", "charming",
    "compassionate", "confident", "cool-headed", "courteous", "creative", "delicate", "determined", "diligent", "energetic",
    "faithful", "fearless", "friendly", "generous", "gentle", "happy", "honorable", "humble", "imaginative", "impatient",
    "independent", "inquisitive", "inspiring", "intelligent", "jovial", "kind", "lively", "loyal", "methodical",
    "mischievous", "optimistic", "outgoing", "patient", "playful", "polite", "quick-witted", "realistic", "romantic",
    "shiny", "sincere", "strong", "stubborn", "sweet", "tender", "thoughtful", "unpredictable", "vibrant", "wise"
}



articles = {
    "a", "an", "the", "this", "that", "these", "those"
}


propernouns = {
    "Alice", "Paris", "John", "New York", "Amazon", "Berlin", "Tesla", "Google", "Harvard", "Shakespeare",
    "Himalayas", "Netflix", "Microsoft", "Italy", "Sophie", "Sydney", "Mount Everest", "Apple", "Boeing",
    "Leonardo", "Cambridge", "Oxford", "Disney", "Nile", "Ganges", "Venice", "Louvre", "Smithsonian", "Princeton",
    "Beijing", "Tokyo", "Singapore", "Bali", "Hollywood", "Elon Musk", "Coca-Cola", "Mercedes", "Beethoven",
    "Einstein", "Mozart", "Socrates", "Da Vinci", "Monet", "Picasso", "Dante", "Renaissance", "Florence",
    "Galapagos", "Amazon Rainforest", "Barcelona", "Madrid", "Rome", "Cairo", "Dubai", "London", "Bangkok",
    "Chicago", "San Francisco", "Los Angeles", "Washington", "Tesla", "Ford", "Harley-Davidson", "Versailles",
    "Statue of Liberty", "Great Wall of China", "Eiffel Tower", "Big Ben", "Machu Picchu", "Christ the Redeemer",
    "Taj Mahal", "Niagara Falls", "Mount Fuji", "Sahara", "Gobi Desert", "Serengeti", "Amazon Basin", "Andes",
    "Rocky Mountains", "Alps", "Pyrenees", "Carpathians", "Victoria Falls", "Yellowstone", "Yosemite",
    "Grand Canyon", "Antarctica", "Arctic", "Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Mediterranean Sea",
    "Bering Sea", "Baltic Sea", "Caribbean Sea", "Galileo", "Newton", "Curie", "Tesla", "Pasteur", "Faraday",
    "Hawking", "Darwin", "Edison", "Marconi", "Roosevelt", "Churchill", "Lincoln", "Washington", "Jefferson",
    "Napoleon", "Caesar", "Cleopatra", "Alexander the Great", "Genghis Khan", "Attila", "Joan of Arc",
    "Martin Luther King Jr.", "Mandela", "Gandhi", "Mother Teresa", "Buddha", "Confucius", "Aristotle",
    "Plato", "Zoroaster", "Hercules", "Odysseus", "Achilles", "Helen of Troy", "Zeus", "Athena", "Poseidon",
    "Apollo", "Aphrodite", "Hera", "Hermes", "Hephaestus", "Ares", "Dionysus", "Thor", "Odin", "Loki",
    "Freya", "Frigg", "Balder", "Tyr", "Fenrir", "Jormungandr", "Yggdrasil", "Valhalla", "Asgard",
    "Midgard", "Helheim", "Surtur", "Niflheim", "Muspelheim", "Vanaheim", "Alfheim", "Svartalfheim",
    "Atlantis", "El Dorado", "Camelot", "Avalon", "Excalibur", "Merlin", "Lancelot", "Guinevere",
    "King Arthur", "Sir Galahad", "Sir Gawain", "Mordred", "Morgana", "Robin Hood", "Maid Marian",
    "Sherwood Forest", "Nottingham", "Windsor", "Buckingham Palace", "Westminster Abbey", "Stonehenge",
    "Pyramids of Giza", "Sphinx", "Luxor", "Valley of the Kings", "Tutankhamun", "Ramses", "Cleopatra's Needle",
    "Vatican City", "Sistine Chapel", "St. Peter's Basilica", "Colosseum", "Forum", "Pantheon", "Trevi Fountain",
    "Pompeii", "Herculaneum", "Mount Vesuvius", "Acropolis", "Parthenon", "Delphi", "Olympia", "Sparta",
    "Troy", "Iliad", "Odyssey", "Homer", "Sappho", "Sophocles", "Euripides", "Aeschylus", "Aristophanes",
    "Herodotus", "Thucydides", "Pericles", "Alexander", "Leonidas", "Xerxes", "Darius", "Solon", "Hippocrates",
    "Pythagoras", "Euclid", "Archimedes", "Hypatia", "Heron", "Cleisthenes", "Draco", "Plutarch", "Cicero",
    "Seneca", "Ovid", "Virgil", "Horace", "Julius Caesar", "Brutus", "Mark Antony", "Augustus", "Nero",
    "Caligula", "Tiberius", "Hadrian", "Trajan", "Marcus Aurelius", "Commodus", "Diocletian", "Constantine",
    "Byzantium", "Hagia Sophia", "Justinian", "Theodora", "Belisarius", "Attila the Hun", "Alaric",
    "Theodosius", "Charlemagne", "Clovis", "Pepin", "Roland", "Eleanor of Aquitaine", "Richard the Lionheart",
    "Saladin", "Genghis Khan", "Kublai Khan", "Marco Polo", "Ibn Battuta", "Mansa Musa", "Timbuktu",
    "Aztec", "Maya", "Inca", "Montezuma", "Pachacuti", "Atahualpa", "Cuzco", "Machu Picchu", "Lake Titicaca",
    "Teotihuacan", "Tikal", "Chichen Itza", "Copan", "Uxmal", "Palenque", "Nazca", "Nazca Lines",
    "Moai", "Easter Island", "Rapa Nui", "Polynesia", "Fiji", "Samoa", "Tonga", "Hawaii", "Mauna Loa",
    "Haleakala", "Auckland", "Wellington", "Christchurch", "Sydney Opera House", "Melbourne",
    "Great Barrier Reef", "Uluru", "Outback", "Tasmania", "Darwin", "Perth", "Brisbane", "Adelaide",
    "Canberra", "Hobart", "Cook", "Magellan", "Cortez", "Pizarro", "Columbus", "Vespucci", "Cabot",
    "Hudson", "Drake", "Balboa", "De Soto", "La Salle", "Champlain", "Ponce de Leon", "Astrolabe",
    "Chronometer", "Sextant", "Celestial Navigation", "Astrolabe"}